//
//  Feedback.swift
//  Accountability Buddy
//
//  Created by Jose Rivas on 11/9/25.
//

import Foundation

/// Struct for INSERTING feedback - only contains fields we send to the database
/// id and created_at are auto-generated by the database
struct FeedbackInsert: Codable {
    let userId: UUID
    let name: String
    let email: String
    let message: String
    
    enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case name
        case email
        case message
    }
}

/// Struct for READING feedback from the database - contains all fields
struct Feedback: Identifiable, Codable {
    let id: UUID
    let userId: UUID
    let name: String
    let email: String
    let message: String
    let createdAt: Date
    
    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case name
        case email
        case message
        case createdAt = "created_at"
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        userId = try container.decode(UUID.self, forKey: .userId)
        name = try container.decode(String.self, forKey: .name)
        email = try container.decode(String.self, forKey: .email)
        message = try container.decode(String.self, forKey: .message)
        
        // Decode date from ISO8601 string
        let dateFormatter = ISO8601DateFormatter()
        dateFormatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        
        let createdAtString = try container.decode(String.self, forKey: .createdAt)
        if let date = dateFormatter.date(from: createdAtString) {
            createdAt = date
        } else {
            dateFormatter.formatOptions = [.withInternetDateTime]
            createdAt = dateFormatter.date(from: createdAtString) ?? Date()
        }
    }
}

